info:
  contact: {}
  description: The MelonWallet microservice responsible for dealing with payment and
    crypto transaction information.
  title: Payment Service
  version: "1.0"
paths: {}
swagger: "2.0"
