name: email-service
version: v1.20230313.1
prod:
  sendgrid_api_key: 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
staging:
  sendgrid_api_key: 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
dev:
  sendgrid_api_key: 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
test:
  sendgrid_api_key: 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
