name: payment-service
version: v1.20230313.1
prod:
  port: 7001
  postgres: postgres://postgres:postgres@localhost:5432/melon_service
  redis: localhost:6379
staging:
  port: 7001
  postgres: postgres://postgres:postgres@localhost:5432/melon_service
  redis: localhost:6379
dev:
  port: 7001
  postgres: postgres://postgres:postgres@localhost:5432/melon_dev
  redis: localhost:6379
test:
  port: 7001
  postgres: postgres://postgres:postgres@localhost:5432/melon_test
  redis: localhost:6379