name: payment-service
version: v1.20220919.1
prod:
  port: 7001
  postgres: postgres://postgres:postgres@localhost:5432/melon_service
  redis: localhost:6379
  sendgrid_api_key: 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
  algolia_id: 5CFQKJHNLK
  search_admin_api_key: 4584d0428bf42bb0ca59ca7d3b7ce403
  search_api_key: 14752a6d8db3f582cd44b362aab57eab
staging:
  port: 7001
  postgres: postgres://postgres:postgres@localhost:5432/melon_service
  redis: localhost:6379
  sendgrid_api_key: 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
  algolia_id: 5CFQKJHNLK
  search_admin_api_key: 4584d0428bf42bb0ca59ca7d3b7ce403
  search_api_key: 14752a6d8db3f582cd44b362aab57eab
dev:
  port: 7001
  postgres: postgres://postgres:postgres@localhost:5432/melon_dev
  redis: localhost:6379
  sendgrid_api_key: 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
  algolia_id: 5CFQKJHNLK
  search_admin_api_key: 4584d0428bf42bb0ca59ca7d3b7ce403
  search_api_key: 14752a6d8db3f582cd44b362aab57eab
test:
  port: 7001
  postgres: postgres://postgres:postgres@localhost:5432/melon_test
  redis: localhost:6379
  sendgrid_api_key: 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
  algolia_id: 5CFQKJHNLK
  search_admin_api_key: 4584d0428bf42bb0ca59ca7d3b7ce403
  search_api_key: 14752a6d8db3f582cd44b362aab57eab
