name: token-config
version: v1.20221102.1
prod:
  secret: NPl6iLAa1rqBbDLdhZRCAc9dU0gQzzAZr12WObz6uNsjjVV7uo
  alternate_secret: c58WLI3BDpxL9T5mxIjTtUIxbrnqSwAg
  auth_token_period: 24
  refresh_token_period: 24
  registration_period: 30
  whitelist_period: 20
  email_verification_period: 10
staging:
  secret: secret
  alternate_secret: K4SICmxG6MSVdL3wGYuqAbVJdTT6em43
  auth_token_period: 24
  refresh_token_period: 168
  registration_period: 30
  whitelist_period: 20
  email_verification_period: 10
dev:
  secret: secret
  alternate_secret: alternate_secret
  auth_token_period: 24
  refresh_token_period: 168
  registration_period: 20
  whitelist_period: 20
  email_verification_period: 10
test:
  secret: secret
  alternate_secret: alternate_secret
  auth_token_period: 24
  refresh_token_period: 168
  registration_period: 20
  whitelist_period: 20
  email_verification_period: 10