basePath: /api/v1
definitions:
  api.AddTransactionRequest:
    properties:
      amount:
        type: number
      currency:
        type: string
      message:
        maxLength: 200
        type: string
      name:
        type: string
      receiver_id:
        type: integer
      receiver_pk:
        type: string
      sender_id:
        type: integer
      sender_pk:
        type: string
      show_type:
        enum:
        - Public
        - Private
        - Friend
        type: string
      status:
        type: string
    required:
    - amount
    - currency
    - name
    - show_type
    type: object
  api.TransactionResponse:
    properties:
      transaction:
        $ref: '#/definitions/entity.Transaction'
    type: object
  api.UpdateTransactionRequest:
    properties:
      message:
        maxLength: 200
        type: string
      name:
        type: string
      show_type:
        enum:
        - Public
        - Private
        - Friend
        type: string
      status:
        type: string
    required:
    - name
    - show_type
    type: object
  entity.Transaction:
    properties:
      amount:
        type: number
      createdAt:
        type: string
      currency:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      message:
        maxLength: 200
        type: string
      name:
        type: string
      receiver_id:
        type: integer
      receiver_pk:
        type: string
      sender_id:
        type: integer
      sender_pk:
        type: string
      show_type:
        type: string
      status:
        type: string
      updatedAt:
        type: string
    required:
    - amount
    - currency
    - name
    - receiver_pk
    - sender_pk
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    email: support@melonnetwork.io
    name: API Support
    url: https://melonnetwork.io
  description: This is backend server for Melon Wallet..
  title: Melon Wallet Service API
  version: "1.0"
paths:
  /transaction:
    delete:
      consumes:
      - application/json
      description: Delete a transaction
      operationId: delete-transaction
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.TransactionResponse'
        "400":
          description: ""
        "401":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      security:
      - ApiKeyAuth: []
      summary: Delete a transaction
      tags:
      - transactions
    get:
      consumes:
      - application/json
      description: List all transactions of requester
      operationId: list-transactions
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.TransactionResponse'
            type: array
        "400":
          description: ""
        "401":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      security:
      - ApiKeyAuth: []
      summary: List all transactions of requester
      tags:
      - transactions
    post:
      consumes:
      - application/json
      description: Add a transaction to account
      operationId: add-transaction
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Transaction Data
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/api.AddTransactionRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/api.TransactionResponse'
        "400":
          description: ""
        "401":
          description: ""
        "404":
          description: ""
      security:
      - ApiKeyAuth: []
      summary: Add a transaction to account
      tags:
      - transactions
    put:
      consumes:
      - application/json
      description: Update a transaction
      operationId: update-transaction
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Transaction Data
        in: body
        name: transaction
        required: true
        schema:
          $ref: '#/definitions/api.UpdateTransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.TransactionResponse'
        "400":
          description: ""
        "401":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      security:
      - ApiKeyAuth: []
      summary: Update a transaction
      tags:
      - transactions
  /transaction/:id:
    get:
      consumes:
      - application/json
      description: Get a transaction
      operationId: get-transaction
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Transaction ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.TransactionResponse'
        "400":
          description: ""
        "401":
          description: ""
        "404":
          description: ""
      security:
      - ApiKeyAuth: []
      summary: Get a transaction
      tags:
      - transactions
  /transaction/user/:id:
    get:
      consumes:
      - application/json
      description: List all transactions of an account
      operationId: list-transactions-by-user
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.TransactionResponse'
            type: array
        "400":
          description: ""
        "401":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      security:
      - ApiKeyAuth: []
      summary: List all transactions of an account
      tags:
      - transactions
swagger: "2.0"
